# Inter-Coder Reliability — Step 1

Sentence-level reliability for the binary task of detecting whether a sentence contains any social-group reference. Each outlet's reliability sample was coded independently by two or more annotators (anonymised as A1, A2, ..., with the same ID across outlets and in the step 2 notebook). Reliability is reported as Krippendorff's α (Krippendorff 2004), computed across all annotators per outlet.

In [1]:
import ast
import json
from itertools import combinations
from pathlib import Path

import numpy as np
import pandas as pd
import krippendorff

In [2]:
BASE_DIR = Path('../data/manual_annotations/step_1')
OUTPUT_DIR = Path('./icr/')

OUTLETS = [
    # (display_name, country, folder)
    ('Le Figaro',              'France',  'figaro'),
    ('Le Monde',               'France',  'monde'),
    ('Le Monde diplomatique',  'France',  'mondediplo'),
    ('Le Parisien',            'France',  'parisien'),
    ('Médiapart',              'France',  'mediapart'),
    ('Libération',             'France',  'libe'),
    ('Bild',                   'Germany', 'bild'),
    ('Frankfurter Allgemeine', 'Germany', 'faz'),
    ('Spiegel',                'Germany', 'spiegel'),
    ('Süddeutsche Zeitung',    'Germany', 'sz'),
    ('Die Welt',               'Germany', 'welt'),
    ('Die Zeit',               'Germany', 'zeit'),
]

# Fixed annotator IDs shared by the step 1 and step 2 notebooks: step 1 annotators first
# (A1-A5), then the annotators who only worked on step 2 (A6-A7).
ANNOTATORS = ['elisa', 'isabelle', 'mathieu', 'selma', 'theres', 'celine', 'stella']
ANNOTATOR_IDS = {name: f'A{i}' for i, name in enumerate(ANNOTATORS, start=1)}

## Data loading

Each outlet folder contains one Doccano JSONL file per annotator. Files within an outlet are row-aligned by sentence position. For each sentence, the annotator's spans are reduced to a binary indicator (1 if any span was marked, 0 otherwise).

In [3]:
EMPTY_TOKENS = {0, 0.0, '0', '', '[]', '0.0', 'nan', None}


def has_annotation(label_field) -> int:
    if isinstance(label_field, list):
        return 1 if any(isinstance(s, list) and len(s) >= 2 for s in label_field) else 0
    try:
        if pd.isna(label_field):
            return 0
    except (TypeError, ValueError):
        pass
    if label_field in EMPTY_TOKENS:
        return 0
    s = str(label_field).strip()
    if s in EMPTY_TOKENS:
        return 0
    try:
        parsed = ast.literal_eval(s)
    except (ValueError, SyntaxError):
        return 0
    return 1 if isinstance(parsed, list) and any(
        isinstance(x, list) and len(x) >= 2 for x in parsed
    ) else 0


def load_outlet(folder_name: str):
    """Load all annotator JSONL files from an outlet folder.

    Returns (n_annotators, binary_matrix). Annotator identities are not retained;
    files are loaded in alphabetical order and treated as anonymous rows.
    """
    folder = BASE_DIR / folder_name
    files = sorted(folder.glob('*.jsonl'))
    if not files:
        raise FileNotFoundError(f'No JSONL files in {folder}')

    rows_by_file = []
    for p in files:
        with open(p, 'r', encoding='utf-8') as f:
            rows_by_file.append([json.loads(line) for line in f if line.strip()])

    n = min(len(rs) for rs in rows_by_file)
    binary_matrix = [[has_annotation(rs[i].get('label', [])) for i in range(n)]
                     for rs in rows_by_file]
    return len(files), binary_matrix

## Per-outlet α calculation

Country and overall rows pool the sentences of all outlets into one reliability matrix. Outlets were coded by different numbers of annotators, so the matrix is padded with missing values, which Krippendorff's α handles natively. `# Annotators` is the number of distinct annotators in the pooled outlets.

In [4]:
def alpha_nominal(matrix) -> float:
    return round(float(krippendorff.alpha(reliability_data=matrix, level_of_measurement='nominal')), 4)


def pool(matrices):
    """Stack outlets side by side (sentences as columns), padding missing annotators with NaN."""
    n_rows = max(len(m) for m in matrices)
    blocks = [np.vstack([np.asarray(m, dtype=float),
                         np.full((n_rows - len(m), len(m[0])), np.nan)]) for m in matrices]
    return np.hstack(blocks)


def annotator_names(folder: str) -> set:
    return {p.stem.lower() for p in (BASE_DIR / folder).glob('*.jsonl')}


results = []
loaded = {}

for country in ['France', 'Germany']:
    country_outlets = [(d, f) for d, c, f in OUTLETS if c == country]
    for display, folder in country_outlets:
        n_annotators, binary_matrix = load_outlet(folder)
        results.append({
            'Outlet':         display,
            'Country':        country,
            'Krippendorff α': alpha_nominal(binary_matrix),
            '# Sentences':    len(binary_matrix[0]),
            '# Annotators':   n_annotators,
        })
        loaded[display] = (n_annotators, binary_matrix)
    pooled = pool([loaded[d][1] for d, _ in country_outlets])
    results.append({
        'Outlet':         f'{country} (all outlets)',
        'Country':        country,
        'Krippendorff α': alpha_nominal(pooled),
        '# Sentences':    pooled.shape[1],
        '# Annotators':   len(set().union(*(annotator_names(f) for _, f in country_outlets))),
    })

pooled = pool([m for _, m in loaded.values()])
results.append({
    'Outlet':         'Overall',
    'Country':        'All',
    'Krippendorff α': alpha_nominal(pooled),
    '# Sentences':    pooled.shape[1],
    '# Annotators':   len(set().union(*(annotator_names(f) for _, _, f in OUTLETS))),
})

df_outlets = pd.DataFrame(results)
df_outlets.to_csv(OUTPUT_DIR / 'icr_step1_by_outlet.csv', index=False)
df_outlets

                    Outlet  Country  Krippendorff α  # Sentences  # Annotators
0                Le Figaro   France          0.9141          300             2
1                 Le Monde   France          0.9444          300             2
2    Le Monde diplomatique   France          0.8944         1200             2
3              Le Parisien   France          0.6541          300             2
4                Médiapart   France          0.7442         1200             2
5               Libération   France          0.7568         1206             4
6     France (all outlets)   France          0.7986         4506             4
7                     Bild  Germany          0.6757          300             5
8   Frankfurter Allgemeine  Germany          0.7035          300             2
9                  Spiegel  Germany          0.6820          300             2
10     Süddeutsche Zeitung  Germany          0.7431          300             2
11                Die Welt  Germany          0.6280          300             2
12                Die Zeit  Germany          0.7546          300             5
13   Germany (all outlets)  Germany          0.7071         1800             5
14                 Overall      All          0.7701         6306             5

## Printout

In [5]:
print(f'{"Newspaper":<28} {"α":>6}  {"N":>6}  {"coders":>6}')
print('-' * 56)
for country_name, code in [('French Newspapers', 'France'), ('German Newspapers', 'Germany')]:
    print(country_name)
    sub = df_outlets[df_outlets['Country'] == code]
    for _, r in sub.iterrows():
        print(f'  {r["Outlet"]:<26} {r["Krippendorff α"]:>6.2f}  '
              f'{r["# Sentences"]:>6,}  {r["# Annotators"]:>6}')
print('-' * 56)
r = df_outlets[df_outlets['Outlet'] == 'Overall'].iloc[0]
print(f'  {"Overall":<26} {r["Krippendorff α"]:>6.2f}  {r["# Sentences"]:>6,}  {r["# Annotators"]:>6}')

Newspaper                         α       N  coders
--------------------------------------------------------
French Newspapers
  Le Figaro                    0.91     300       2
  Le Monde                     0.94     300       2
  Le Monde diplomatique        0.89   1,200       2
  Le Parisien                  0.65     300       2
  Médiapart                    0.74   1,200       2
  Libération                   0.76   1,206       4
  France (all outlets)         0.80   4,506       4
German Newspapers
  Bild                         0.68     300       5
  Frankfurter Allgemeine       0.70     300       2
  Spiegel                      0.68     300       2
  Süddeutsche Zeitung          0.74     300       2
  Die Welt                     0.63     300       2
  Die Zeit                     0.75     300       5
  Germany (all outlets)        0.71   1,800       5
--------------------------------------------------------
  Overall                      0.77   6,306       5

## Pairwise breakdown

α for every pair of annotators within each outlet (outlets with two annotators have a single pair, equal to the outlet α). Annotator IDs are the same across outlets, so the outlet × pair table separates the outlet from the annotator pair: a column shows one pair across outlets, a row shows the pairs within one outlet.

In [6]:
def file_annotators(folder: str) -> list:
    """Annotator names in the row order of load_outlet's matrix (files sorted alphabetically)."""
    return [p.stem.lower() for p in sorted((BASE_DIR / folder).glob('*.jsonl'))]


pair_rows = []
for display, country, folder in OUTLETS:
    n_ann, matrix = loaded[display]
    names = file_annotators(folder)
    assert len(names) == n_ann and set(names) <= set(ANNOTATOR_IDS), names
    for i, j in combinations(range(n_ann), 2):
        pair_rows.append({
            'Outlet':         display,
            'Country':        country,
            'Pair':           f'{ANNOTATOR_IDS[names[i]]} + {ANNOTATOR_IDS[names[j]]}',
            'Krippendorff α': alpha_nominal([matrix[i], matrix[j]]),
            'N':              len(matrix[0]),
        })

df_pairs = pd.DataFrame(pair_rows)
df_pairs.to_csv(OUTPUT_DIR / 'icr_step1_by_annotator_pair.csv', index=False)
df_pairs.set_index(['Outlet', 'Pair'])

                                Country  Krippendorff α     N
Outlet                 Pair
Le Figaro              A3 + A4   France          0.9141   300
Le Monde               A3 + A4   France          0.9444   300
Le Monde diplomatique  A3 + A4   France          0.8944  1200
Le Parisien            A3 + A4   France          0.6541   300
Médiapart              A3 + A4   France          0.7442  1200
Libération             A1 + A2   France          0.7526  1206
                       A1 + A3   France          0.7221  1206
                       A1 + A4   France          0.8469  1206
                       A2 + A3   France          0.7225  1206
                       A2 + A4   France          0.7643  1206
                       A3 + A4   France          0.7248  1206
Bild                   A1 + A2  Germany          0.7506   300
                       A1 + A3  Germany          0.7152   300
                       A1 + A4  Germany          0.5919   300
                       A1 + A5  Germany          0.6003   300
                       A2 + A3  Germany          0.9051   300
                       A2 + A4  Germany          0.5709   300
                       A2 + A5  Germany          0.7368   300
                       A3 + A4  Germany          0.5556   300
                       A3 + A5  Germany          0.7203   300
                       A4 + A5  Germany          0.5732   300
Frankfurter Allgemeine A2 + A3  Germany          0.7035   300
Spiegel                A2 + A3  Germany          0.6820   300
Süddeutsche Zeitung    A1 + A4  Germany          0.7431   300
Die Welt               A1 + A4  Germany          0.6280   300
Die Zeit               A1 + A2  Germany          0.7561   300
                       A1 + A3  Germany          0.8051   300
                       A1 + A4  Germany          0.7524   300
                       A1 + A5  Germany          0.6912   300
                       A2 + A3  Germany          0.8128   300
                       A2 + A4  Germany          0.8260   300
                       A2 + A5  Germany          0.7330   300
                       A3 + A4  Germany          0.7580   300
                       A3 + A5  Germany          0.7134   300
                       A4 + A5  Germany          0.6961   300

## Outlet × annotator pair table

Rows: outlets (grouped by country) with their number of sentences and all-annotator α (main result). Columns: annotator pairs. Empty cells: the pair did not code that outlet.

In [7]:
PAIRS = sorted(df_pairs['Pair'].unique(), key=lambda s: [int(x[1:]) for x in s.split(' + ')])

wide = df_pairs.pivot(index='Outlet', columns='Pair', values='Krippendorff α')[PAIRS]
outlet_info = df_outlets.set_index('Outlet')[['Country', '# Sentences', 'Krippendorff α']]
wide = outlet_info.loc[[d for d, _, _ in OUTLETS]].join(wide)
wide = wide.rename(columns={'Krippendorff α': 'All annotators'})
wide.to_csv(OUTPUT_DIR / 'icr_step1_outlet_by_pair.csv')


def fmt(a):
    return '' if pd.isna(a) else f'{a:.2f}'


n_cols = 3 + len(PAIRS)
lines = [
    r'\begin{table}[htbp]',
    r'\centering',
    r'\scriptsize',
    r'\begin{threeparttable}',
    r'\caption{Inter-coder reliability for step 1 by outlet and annotator pair.}',
    r'\label{tab:icr_step1_outlet_by_pair}',
    r'\begin{tabular}{l r r ' + 'r ' * len(PAIRS) + '}',
    r'\toprule',
    rf' & & & \multicolumn{{{len(PAIRS)}}}{{c}}{{Annotator pair}} \\',
    rf'\cmidrule(lr){{4-{n_cols}}}',
    # one annotator of the pair per header row, to keep the columns narrow
    ' & '.join(['', '', ''] + [p.split(' + ')[0] for p in PAIRS]) + r' \\',
    ' & '.join(['', '$N$', 'All'] + [p.split(' + ')[1] for p in PAIRS]) + r' \\',
]
for country, heading in [('France', 'French newspapers'), ('Germany', 'German newspapers')]:
    lines += [r'\midrule', rf'\multicolumn{{{n_cols}}}{{l}}{{\textbf{{{heading}}}}} \\']
    for outlet, r in wide[wide['Country'] == country].iterrows():
        cells_ = [r'\quad ' + outlet, f'{r["# Sentences"]:,}', fmt(r['All annotators'])] + [fmt(r[p]) for p in PAIRS]
        lines.append(' & '.join(cells_) + r' \\')
lines += [
    r'\bottomrule',
    r'\end{tabular}',
    r'\begin{tablenotes}[flushleft]',
    r'\footnotesize',
    r"\item \textit{Note:} Krippendorff's $\alpha$. All: $\alpha$ across all annotators of the outlet. "
    r'Annotators are identified by the same ID across outlets. Empty cells: the pair did not code the outlet.',
    r'\end{tablenotes}',
    r'\end{threeparttable}',
    r'\end{table}',
    '',
]
(OUTPUT_DIR / 'icr_step1_outlet_by_pair.tex').write_text('\n'.join(lines), encoding='utf-8')
wide

,Country,# Sentences,All annotators,A1 + A2,A1 + A3,A1 + A4,A1 + A5,A2 + A3,A2 + A4,A2 + A5,A3 + A4,A3 + A5,A4 + A5
Outlet,,,,,,,,,,,,,
Le Figaro,France,300,0.9141,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.9141,NaN,NaN
Le Monde,France,300,0.9444,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.9444,NaN,NaN
Le Monde diplomatique,France,1200,0.8944,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.8944,NaN,NaN
Le Parisien,France,300,0.6541,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.6541,NaN,NaN
Médiapart,France,1200,0.7442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.7442,NaN,NaN
Libération,France,1206,0.7568,0.7526,0.7221,0.8469,NaN,0.7225,0.7643,NaN,0.7248,NaN,NaN
Bild,Germany,300,0.6757,0.7506,0.7152,0.5919,0.6003,0.9051,0.5709,0.7368,0.5556,0.7203,0.5732
Frankfurter Allgemeine,Germany,300,0.7035,NaN,NaN,NaN,NaN,0.7035,NaN,NaN,NaN,NaN,NaN
Spiegel,Germany,300,0.6820,NaN,NaN,NaN,NaN,0.6820,NaN,NaN,NaN,NaN,NaN
Süddeutsche Zeitung,Germany,300,0.7431,NaN,NaN,0.7431,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Die Welt,Germany,300,0.6280,NaN,NaN,0.6280,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Die Zeit,Germany,300,0.7546,0.7561,0.8051,0.7524,0.6912,0.8128,0.8260,0.7330,0.7580,0.7134,0.6961